fix requirements omissions
jeffgyf/EarTrainer pull request #3
Opened 2019-02-05 14:48 UTC by wfnuser

Fixes #2

2019-02-05 23:34 UTC, jeffgyf requested changes

2019-02-05 23:34 UTC, jeffgyf commented on main.py
> +        print(reduce((lambda s,i: s+" "+i), map(lambda e: pitch_names[e], pitches)))
你是dog吧这都要改，我的用法明显是和sicp中定义相同的标准用法。话说这样明显更奇怪了，让人搞不清初始值是什么，而且逻辑和给初始值有微妙的区别，一开始我还以为会多一个前置空格了。

不予批准！

2019-02-06 16:27 UTC, wfnuser commented on main.py
> +        print(reduce((lambda s,i: s+" "+i), map(lambda e: pitch_names[e], pitches)))
What a dog project owner! Refusing pull request is ok, but calling someone who would like to contribute to this project dog is definitely not ok.

2019-02-06 16:33 UTC, wfnuser commented
Has been updated.

2019-02-07 06:37 UTC, merged